# Generated by Django 5.0.4 on 2024-04-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='opening_time',
        ),
    ]
