# Generated by Django 5.0.4 on 2024-05-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
