# Generated by Django 5.0.4 on 2024-04-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine'),
        ('app', '0003_pet'),
        ('app', '0003_vet'),
    ]

    operations = [
    ]
