# Generated by Django 5.0.4 on 2024-04-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine'),
        ('app', '0004_products'),
    ]

    operations = [
    ]
