# Generated by Django 5.1.dev20240412151528 on 2024-05-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine'),
        ('app', '0004_vet'),
    ]

    operations = [
    ]
