# Generated by Django 5.0.4 on 2024-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine'),
        ('app', '0003_product'),
        ('app', '0004_pet_client'),
    ]

    operations = [
    ]
