# Generated by Django 5.0.4 on 2024-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0003_medicine_0003_pet_0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(to='app.product'),
        ),
    ]
