# Generated by Django 4.2.4 on 2024-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine_pet_product_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.FloatField(),
        ),
    ]
