# Generated by Django 5.0.4 on 2024-04-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine'),
        ('app', '0004_product'),
    ]

    operations = [
    ]
