# Generated by Django 5.0.4 on 2024-05-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
        ('app', '0004_remove_vet_closing_time_remove_vet_opening_time'),
    ]

    operations = [
    ]
