# Generated by Django 5.0.4 on 2024-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0003_medicine_0003_product_0004_pet_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medicines',
            field=models.ManyToManyField(to='app.medicine'),
        ),
    ]
