# Generated by Django 5.0.4 on 2024-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_medicine_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='floor_apartament',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
