# Generated by Django 5.0.4 on 2024-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet'),
        ('app', '0005_merge_0003_medicine_0004_products'),
    ]

    operations = [
    ]
