# Generated by Django 5.0.4 on 2024-05-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0003_medicine_0003_pet_0003_vet'),
        ('app', '0005_client_products'),
    ]

    operations = [
    ]
