# Generated by Django 5.0.4 on 2024-05-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_provider'),
        ('app', '0005_merge_20240501_2038'),
    ]

    operations = [
    ]
