# Generated by Django 5.0.4 on 2024-05-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vet'),
        ('app', '0006_merge_0003_pet_0005_merge_0003_medicine_0004_products'),
    ]

    operations = [
    ]
