# Generated by Django 5.0.4 on 2024-05-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicine'),
        ('app', '0006_merge_0003_provider_0005_merge_20240501_2038'),
    ]

    operations = [
    ]
