# Generated by Django 5.0.4 on 2024-05-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20240503_1215'),
        ('app', '0006_pet_medicines'),
    ]

    operations = [
    ]
