# Generated by Django 5.0.4 on 2024-04-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_med'),
        ('app', '0006_merge_0003_pet_0005_veterinary'),
    ]

    operations = [
    ]
