# Generated by Django 5.0.4 on 2024-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20240503_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vets',
            field=models.ManyToManyField(to='app.vet'),
        ),
    ]
