# Generated by Django 5.0.4 on 2024-05-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
