# Generated by Django 5.0.4 on 2024-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0004_med_0006_merge_0003_pet_0005_veterinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
