# Generated by Django 5.0.4 on 2024-05-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pet_medicines'),
        ('app', '0007_pet_vets'),
    ]

    operations = [
    ]
