# Generated by Django 5.0.4 on 2024-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0004_med_0006_merge_0003_pet_0005_veterinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('RABBIT', 'Conejo'), ('BIRD', 'Pájaro'), ('FISH', 'Pez'), ('OTHER', 'Otro')], max_length=10),
        ),
    ]
