# Generated by Django 5.0.4 on 2024-05-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet'),
        ('app', '0007_merge_20240501_2220'),
    ]

    operations = [
    ]
