# Generated by Django 5.0.4 on 2024-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0006_merge_20240503_1215_0006_pet_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
