# Generated by Django 5.0.4 on 2024-05-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_provider_product_provider'),
        ('app', '0007_merge_20240503_2023'),
        ('app', '0008_merge_0006_pet_medicines_0007_pet_vets'),
    ]

    operations = [
    ]
