# Generated by Django 5.0.4 on 2024-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0003_pet_0007_merge_20240501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='speciality',
            field=models.CharField(choices=[('General', 'General'), ('Surgeon', 'Surgeon'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist')], default='General', max_length=15),
        ),
    ]
