# Generated by Django 5.0.4 on 2024-05-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pet_breed'),
        ('app', '0008_product_stock'),
    ]

    operations = [
    ]
