# Generated by Django 5.0.4 on 2024-05-25 00:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vet_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vet',
            name='speciality',
            field=models.CharField(choices=[('Oftalmologia', 'Oftalmologia'), ('Quimioterapia', 'Quimioterapia'), ('Radiologia', 'Radiologia'), ('Ecocardiografias', 'Ecocardiografias'), ('Traumatologia', 'Traumatologia'), ('Ecografias', 'Ecografias'), ('Urgencias', 'Urgencias')], default=app.models.Speciality['Urgencias'], max_length=100),
        ),
    ]
