# Generated by Django 5.0.4 on 2024-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vet_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='speciality',
            field=models.CharField(max_length=15),
        ),
    ]
