# Generated by Django 5.0.4 on 2024-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240503_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='specialty',
            field=models.CharField(choices=[('General', 'General'), ('Cirugía', 'Cirugía'), ('Dermatología', 'Dermatología'), ('Ortopedia', 'Ortopedia'), ('Cardiología', 'Cardiología'), ('Oftalmología', 'Oftalmología'), ('Neurología', 'Neurología')], default='General', max_length=50),
        ),
    ]
