# Generated by Django 5.0.4 on 2024-05-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pet_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medicines',
            field=models.ManyToManyField(to='app.medicine'),
        ),
    ]
