# Generated by Django 5.0.4 on 2024-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pet_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vets',
            field=models.ManyToManyField(blank=True, to='app.vet'),
        ),
    ]
