# Generated by Django 5.0.4 on 2024-05-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_provider_address'),
        ('app', '0010_alter_pet_breed'),
    ]

    operations = [
    ]
