# Generated by Django 5.0.4 on 2024-05-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pet_weight'),
        ('app', '0010_vet_specialty'),
    ]

    operations = [
    ]
