# Generated by Django 5.0.4 on 2024-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pet_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='pets',
            field=models.ManyToManyField(to='app.pet'),
        ),
    ]
