# Generated by Django 5.0.4 on 2024-05-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pet_breed'),
        ('app', '0010_alter_provider_address'),
        ('app', '0010_alter_vet_speciality'),
    ]

    operations = [
    ]
