# Generated by Django 5.0.4 on 2024-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pet_vets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
