# Generated by Django 5.0.4 on 2024-06-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_pet_breed'),
        ('app', '0012_remove_pet_owner_alter_pet_breed'),
    ]

    operations = [
    ]
