# Generated by Django 5.0.4 on 2024-06-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20240602_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird')], default='Dog', max_length=100),
        ),
    ]
