name: ci

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
                  cache: 'pip'
            - run: pip install -r requirements.txt

            - name: Install playwright
              run: python -m playwright install --with-deps firefox

            - name: Run static test
              run: ruff check

            - name: Run unit and integration tests
              run: coverage run --source="./app" --omit="./app/migrations/**" manage.py test app
              env:
                DBENGINE : django.db.backends.sqlite3
                DBNAME : db.sqlite3

            - name: Check coverage
              run: coverage report --fail-under=92

            - name: Run e2e tests
              run: python manage.py test functional_tests
              env:
                DBENGINE : django.db.backends.sqlite3
                DBNAME : db.sqlite3
